# Rulefit

Rulefitに関して
- [Predictive learning via rule ensembles](https://arxiv.org/abs/0811.1679)
- [Interpretable Machine Learning – A Guide for Making Black Box Models Explainable](https://christophm.github.io/interpretable-ml-book/rulefit.html)（[日本語](https://hacarus.github.io/interpretable-ml-book-ja/rulefit.html)）

[ドキュメント - RuleFit](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/rulefit.html)  
[Python API - H2ORuleFitEstimator](https://docs.h2o.ai/h2o/latest-stable/h2o-py/docs/modeling.html#h2orulefitestimator)

In [1]:
import h2o
print(h2o.__version__)
from h2o.estimators import H2ORuleFitEstimator

3.36.0.4

In [2]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321 ..... not found.
Attempting to start a local H2O server...
  Java Version: java version "11.0.9" 2020-10-20 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.9+7-LTS); Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.9+7-LTS, mixed mode)
  Starting server from /opt/anaconda3/lib/python3.8/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /var/folders/50/glkvvhjx03g22fwy2r0tgylr0000gn/T/tmpiy6k_by2
  JVM stdout: /var/folders/50/glkvvhjx03g22fwy2r0tgylr0000gn/T/tmpiy6k_by2/h2o_YShimada_MBP16_started_from_python.out
  JVM stderr: /var/folders/50/glkvvhjx03g22fwy2r0tgylr0000gn/T/tmpiy6k_by2/h2o_YShimada_MBP16_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.
Warning: Your H2O cluster version is too old (10 months and 7 days)!Please download and install the latest version from http://h2o.ai/download/

--------------------------  -------------------------------------
H2O_cluster_uptime:         02 secs
H2O_cluster_timezone:       Asia/Tokyo
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.36.0.4
H2O_cluster_version_age:    10 months and 7 days !!!
H2O_cluster_name:           H2O_from_python_YShimada_MBP16_3h1fkf
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    8 Gb
H2O_cluster_total_cores:    16
H2O_cluster_allowed_cores:  16
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.8.13 final
--------------------------  -------------------------------------

In [3]:
f = "https://h2oai-jp-public.s3.ap-northeast-1.amazonaws.com/sample_data/UCI_CreditCard/UCI_Credit_Card3.csv"
df = h2o.import_file(path=f, col_types={'ID': "enum", 'default_payment_next_month': "enum"})
df.shape

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

(30000, 25)

In [4]:
df.describe()

Rows:30000
Cols:25

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default_payment_next_month
type,enum,int,enum,enum,enum,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,int,enum
mins,,10000.0,,,,21.0,-2.0,-2.0,-2.0,-2.0,-2.0,-2.0,-165580.0,-69777.0,-157264.0,-170000.0,-81334.0,-339603.0,0.0,0.0,0.0,0.0,0.0,0.0,
mean,,167484.32266666667,,,,35.4855,-0.01669999999999999,-0.13376666666666667,-0.1662,-0.2206666666666667,-0.2662,-0.2911,51223.3309,49179.07516666667,47013.1548,43262.94896666666,40311.40096666667,38871.7604,5663.5805,5921.163499999999,5225.6815,4826.076866666666,4799.387633333334,5215.502566666667,
maxs,,1000000.0,,,,79.0,8.0,8.0,8.0,8.0,8.0,8.0,964511.0,983931.0,1664089.0,891586.0,927171.0,961664.0,873552.0,1684259.0,896040.0,621000.0,426529.0,528666.0,
sigma,,129747.6615672024,,,,9.217904068090185,1.1238015279973348,1.1971859730345533,1.1968675684465737,1.1691386224023375,1.1331874060027483,1.1499876256079027,73635.86057552956,71173.76878252834,69349.38742703684,64332.85613391631,60797.15577026487,59554.10753674573,16563.280354025766,23040.870402057233,17606.961469803104,15666.159744032007,15278.305679144789,17777.465775435296,
zeros,,0,,,,0,14737,15730,15764,16455,16947,16286,2008,2506,2870,3195,3506,4020,5249,5396,5968,6408,6703,7173,
missing,0,0,0,345,54,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
0,1,20000.0,M,university,married,24.0,2.0,2.0,-1.0,-1.0,-2.0,-2.0,3913.0,3102.0,689.0,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,M,university,single,26.0,-1.0,2.0,0.0,0.0,0.0,2.0,2682.0,1725.0,2682.0,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,M,university,single,34.0,0.0,0.0,0.0,0.0,0.0,0.0,29239.0,14027.0,13559.0,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,M,university,married,37.0,0.0,0.0,0.0,0.0,0.0,0.0,46990.0,48233.0,49291.0,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,F,university,married,57.0,-1.0,0.0,-1.0,0.0,0.0,0.0,8617.0,5670.0,35835.0,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
5,6,50000.0,F,graduate school,single,37.0,0.0,0.0,0.0,0.0,0.0,0.0,64400.0,57069.0,57608.0,19394.0,19619.0,20024.0,2500.0,1815.0,657.0,1000.0,1000.0,800.0,0
6,7,500000.0,F,graduate school,single,29.0,0.0,0.0,0.0,0.0,0.0,0.0,367965.0,412023.0,445007.0,542653.0,483003.0,473944.0,55000.0,40000.0,38000.0,20239.0,13750.0,13770.0,0
7,8,100000.0,M,university,single,23.0,0.0,-1.0,-1.0,0.0,0.0,-1.0,11876.0,380.0,601.0,221.0,-159.0,567.0,380.0,601.0,0.0,581.0,1687.0,1542.0,0
8,9,140000.0,M,high school,married,28.0,0.0,0.0,2.0,0.0,0.0,0.0,11285.0,14096.0,12108.0,12211.0,11793.0,3719.0,3329.0,0.0,432.0,1000.0,1000.0,1000.0,0
9,10,20000.0,F,high school,single,35.0,-2.0,-2.0,-2.0,-2.0,-1.0,-1.0,0.0,0.0,0.0,0.0,13007.0,13912.0,0.0,0.0,0.0,13007.0,1122.0,0.0,0

In [5]:
# データ分割
frame_train, frame_test = df.split_frame(ratios=[0.8], seed=12345)
frame_train.shape, frame_test.shape

((24059, 25), (5941, 25))

In [6]:
# カラムの役割
x_cols = ['SEX','EDUCATION','MARRIAGE','AGE',
     'PAY_1','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6',
     'BILL_AMT1','BILL_AMT2','BILL_AMT3','BILL_AMT4','BILL_AMT5','BILL_AMT6',
     'PAY_AMT1','PAY_AMT2','PAY_AMT3','PAY_AMT4','PAY_AMT5','PAY_AMT6']
y_col = 'default_payment_next_month'

### モデル作成

In [7]:
rfit = H2ORuleFitEstimator(seed=123)
rfit.train(x=x_cols, y=y_col, training_frame=frame_train, validation_frame=frame_test)

rulefit Model Build progress: |██████████████████████████████████████████████████| (done) 100%
Model Details
=============
H2ORuleFitEstimator :  RuleFit
Model Key:  RuleFit_model_python_1675744537467_1


Rulefit Model Summary:

,,family,link,regularization,number_of_predictors_total,number_of_active_predictors,number_of_iterations,rule_ensemble_size,number_of_trees,number_of_internal_trees,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,binomial,logit,Lasso (lambda = 1.346E-4 ),427,175,4,399.0,50.0,50.0,0.0,3.0,3.0,0.0,8.0,7.98

ModelMetricsBinomialGLM: rulefit
** Reported on train data. **

MSE: 0.13261185356095365
RMSE: 0.36415910473439167
LogLoss: 0.4249808070290417
Null degrees of freedom: 24058
Residual degrees of freedom: 23883
Null deviance: 25409.37990548039
Residual deviance: 20449.226472623428
AIC: 20801.226472623428
AUC: 0.7816489159880174
AUCPR: 0.5697436875677483
Gini: 0.5632978319760349

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.267804299763515:

                0       1   Error               Rate
0      0  15933.0  2811.0    0.15   (2811.0/18744.0)
1      1   2237.0  3078.0  0.4209    (2237.0/5315.0)
2  Total  18170.0  5889.0  0.2098   (5048.0/24059.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold         value    idx
0                        max f1   0.267804      0.549447  218.0
1                        max f2   0.120087      0.635351  318.0
2                  max f0point5   0.503037      0.589518  127.0
3                  max accuracy   0.508111      0.824390  125.0
4                 max precision   0.891024      1.000000    0.0
5                    max recall   0.025772      1.000000  397.0
6               max specificity   0.891024      1.000000    0.0
7              max absolute_mcc   0.388770      0.426789  165.0
8    max min_per_class_accuracy   0.178049      0.706867  271.0
9   max mean_per_class_accuracy   0.235398      0.716975  235.0
10                      max tns   0.891024  18744.000000    0.0
11                      max fns   0.891024   5313.000000    0.0
12                      max fps   0.002858  18744.000000  399.0
13                      max tps   0.025772   5315.000000  397.0
14                      max tnr   0.891024      1.000000    0.0
15                      max fnr   0.891024      0.999624    0.0
16                      max fpr   0.002858      1.000000  399.0
17                      max tpr   0.025772      1.000000  397.0

Gains/Lift Table: Avg response rate: 22.09 %, avg score: 22.10 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.010017,0.813850,3.906795,3.906795,0.863071,0.837974,0.863071,0.837974,0.039135,0.039135,290.679475,290.679475,0.037374
1,2,0.020034,0.780204,3.625055,3.765925,0.800830,0.796430,0.831950,0.817202,0.036312,0.075447,262.505475,276.592475,0.071125
2,3,0.030010,0.756091,3.508133,3.680232,0.775000,0.767777,0.813019,0.800773,0.034995,0.110442,250.813264,268.023208,0.103240
3,4,0.040027,0.730961,3.399663,3.610017,0.751037,0.743920,0.797508,0.786545,0.034055,0.144497,239.966274,261.001691,0.134093
4,5,0.050002,0.704498,3.583576,3.604742,0.791667,0.716784,0.796342,0.772627,0.035748,0.180245,258.357636,260.474199,0.167174
5,6,0.100004,0.584093,2.889814,3.247278,0.638404,0.650997,0.717373,0.711812,0.144497,0.324741,188.981403,224.727801,0.288463
6,7,0.150006,0.402681,2.189937,2.894831,0.483791,0.488171,0.639512,0.637265,0.109501,0.434243,118.993720,189.483107,0.364834
7,8,0.200008,0.313262,1.648097,2.583148,0.364090,0.351549,0.570657,0.565836,0.082408,0.516651,64.809707,158.314757,0.406429
8,9,0.300012,0.223641,1.194682,2.120326,0.263924,0.264251,0.468412,0.465308,0.119473,0.636124,19.468223,112.032579,0.431419
9,10,0.400017,0.169606,0.857914,1.804723,0.189526,0.194247,0.398691,0.397543,0.085795,0.721919,-14.208646,80.472273,0.413180
10,11,0.500021,0.141179,0.696114,1.583001,0.153782,0.154968,0.349709,0.349028,0.069614,0.791533,-30.388594,58.300100,0.374173
11,12,0.599983,0.116710,0.604177,1.419920,0.133472,0.128416,0.313682,0.312272,0.060395,0.851929,-39.582291,41.992019,0.323386
12,13,0.699988,0.099334,0.481636,1.285872,0.106401,0.107460,0.284069,0.283011,0.048166,0.900094,-51.836433,28.587158,0.256848
13,14,0.799992,0.086228,0.440245,1.180163,0.097257,0.092632,0.260716,0.259213,0.044026,0.944120,-55.975489,18.016278,0.184997
14,15,0.899996,0.070994,0.319836,1.084567,0.070657,0.079161,0.239597,0.239206,0.031985,0.976105,-68.016381,8.456652,0.097691
15,16,1.000000,0.002858,0.238936,1.000000,0.052785,0.056672,0.220915,0.220952,0.023895,1.000000,-76.106355,0.000000,0.000000

ModelMetricsBinomialGLM: rulefit
** Reported on validation data. **

MSE: 0.13508788381446798
RMSE: 0.3675430366834175
LogLoss: 0.4311507477513511
Null degrees of freedom: 5940
Residual degrees of freedom: 5765
Null deviance: 6295.988467440929
Residual deviance: 5122.933184781554
AIC: 5474.933184781554
AUC: 0.7768086127851457
AUCPR: 0.5584472270661128
Gini: 0.5536172255702914

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.2757976701403707:

               0       1   Error              Rate
0      0  3971.0   649.0  0.1405    (649.0/4620.0)
1      1   595.0   726.0  0.4504    (595.0/1321.0)
2  Total  4566.0  1375.0  0.2094   (1244.0/5941.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.275798     0.538576  206.0
1                        max f2   0.100714     0.634237  336.0
2                  max f0point5   0.400471     0.581518  151.0
3                  max accuracy   0.560927     0.822084  105.0
4                 max precision   0.907547     1.000000    0.0
5                    max recall   0.037847     1.000000  392.0
6               max specificity   0.907547     1.000000    0.0
7              max absolute_mcc   0.391697     0.416724  154.0
8    max min_per_class_accuracy   0.172755     0.702498  269.0
9   max mean_per_class_accuracy   0.187724     0.708564  258.0
10                      max tns   0.907547  4620.000000    0.0
11                      max fns   0.907547  1320.000000    0.0
12                      max fps   0.010792  4620.000000  399.0
13                      max tps   0.037847  1321.000000  392.0
14                      max tnr   0.907547     1.000000    0.0
15                      max fnr   0.907547     0.999243    0.0
16                      max fpr   0.010792     1.000000  399.0
17                      max tpr   0.037847     1.000000  392.0

Gains/Lift Table: Avg response rate: 22.24 %, avg score: 21.76 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.010099,0.817994,3.597880,3.597880,0.800000,0.838132,0.800000,0.838132,0.036336,0.036336,259.788039,259.788039,0.033739
1,2,0.020030,0.782306,3.735088,3.665908,0.830508,0.801778,0.815126,0.820108,0.037093,0.073429,273.508770,266.590754,0.068667
2,3,0.030130,0.760299,3.522925,3.617980,0.783333,0.771420,0.804469,0.803788,0.035579,0.109008,252.292455,261.798028,0.101433
3,4,0.040061,0.734648,3.049051,3.476943,0.677966,0.749276,0.773109,0.790275,0.030280,0.139288,204.905118,247.694324,0.127600
4,5,0.050160,0.708352,3.597880,3.501293,0.800000,0.720394,0.778523,0.776205,0.036336,0.175625,259.788039,250.129300,0.161339
5,6,0.100151,0.568079,2.967948,3.235069,0.659933,0.647386,0.719328,0.711904,0.148372,0.323997,196.794847,223.506893,0.287850
6,7,0.150143,0.381380,2.074535,2.848658,0.461279,0.458421,0.633408,0.627504,0.103709,0.427706,107.453541,184.865810,0.356927
7,8,0.200135,0.307001,1.574830,2.530469,0.350168,0.340593,0.562658,0.555837,0.078728,0.506435,57.482980,153.046886,0.393880
8,9,0.300118,0.216254,1.165980,2.075894,0.259259,0.258842,0.461582,0.456894,0.116578,0.623013,16.597976,107.589425,0.415221
9,10,0.400101,0.167307,0.893413,1.780398,0.198653,0.189609,0.395877,0.390101,0.089326,0.712339,-10.658694,78.039832,0.401517
10,11,0.500084,0.139762,0.734416,1.571272,0.163300,0.153098,0.349377,0.342716,0.073429,0.785768,-26.558418,57.127224,0.367370
11,12,0.600067,0.116222,0.635989,1.415435,0.141414,0.127785,0.314727,0.306904,0.063588,0.849357,-36.401104,41.543541,0.320569
12,13,0.700050,0.099543,0.560276,1.293299,0.124579,0.107278,0.287569,0.278393,0.056018,0.905375,-43.972401,29.329916,0.264033
13,14,0.800034,0.085555,0.439135,1.186551,0.097643,0.092396,0.263833,0.255148,0.043906,0.949281,-56.086477,18.655113,0.191922
14,15,0.900017,0.070521,0.280138,1.085857,0.062290,0.078435,0.241444,0.235517,0.028009,0.977290,-71.986201,8.585739,0.099368
15,16,1.000000,0.010792,0.227139,1.000000,0.050505,0.056398,0.222353,0.217608,0.022710,1.000000,-77.286109,0.000000,0.000000

In [8]:
# 学習とテストデータにおけるAUC
rfit.auc(), rfit.auc(valid=True)

(0.7816489159880174, 0.7768086127851457)

In [9]:
# ハイパーパラメータ（デフォルト設定）の確認
rfit.actual_params

{'model_id': 'RuleFit_model_python_1675744537467_1',
 'training_frame': 'py_2_sid_b0e1',
 'validation_frame': 'py_3_sid_b0e1',
 'seed': 123,
 'response_column': 'default_payment_next_month',
 'ignored_columns': ['LIMIT_BAL', 'ID'],
 'algorithm': 'DRF',
 'min_rule_length': 3,
 'max_rule_length': 3,
 'max_num_rules': -1,
 'model_type': 'RULES_AND_LINEAR',
 'weights_column': None,
 'distribution': 'AUTO',
 'rule_generation_ntrees': 50,
 'auc_type': 'AUTO',
 'remove_duplicates': True,
 'lambda': None}

### ルールの確認

In [10]:
# 特徴量重要度（Lassoの回帰係数）とルール（交互作用）の表示
rfit.rule_importance()

Rule Importance:

,,variable,coefficient,support,rule
0,,M0T43N20,0.793195,0.060684,(PAY_2 >= 1.5) & (PAY_5 >= 1.0) & (PAY_AMT3 < 12250.5 or PAY_AMT3 ...
1,,M0T42N16,0.792601,0.002411,(AGE >= 59.5) & (PAY_3 < -0.5 or PAY_3 is NA) & (PAY_AMT1 < 853.5)
2,,M0T28N21,0.511264,0.039486,(PAY_2 < 1.5) & (PAY_3 >= 1.5) & (PAY_AMT1 >= 853.5 or PAY_AMT1 is...
3,,M0T41N18,-0.487634,0.021281,(BILL_AMT1 >= 13204.5) & (PAY_1 >= 1.5) & (PAY_AMT1 < 853.5)
4,,M0T37N21,0.482087,0.097302,(PAY_1 >= 1.5) & (PAY_3 >= -0.5 or PAY_3 is NA) & (PAY_AMT5 < 2832...
5,,"M0T14N15, M0T4N15, M0T22N15, M0T30N15",-0.481257,0.786816,(PAY_1 < 1.5 or PAY_1 is NA) & (PAY_2 < 1.5 or PAY_2 is NA) & (PAY...
6,,M0T46N18,0.476049,0.029968,(PAY_3 < 1.5) & (PAY_4 >= 0.5) & (PAY_AMT5 < 14162.5 or PAY_AMT5 i...
7,,linear.EDUCATION.others,-0.471012,1.000000,
8,,M0T36N13,0.459004,0.251631,(BILL_AMT2 < 4311.5) & (PAY_1 < 1.5 or PAY_1 is NA) & (PAY_2 < 1.5...
9,,M0T17N18,0.436366,0.041315,(BILL_AMT1 >= 2168.5 or BILL_AMT1 is NA) & (PAY_1 >= 1.5) & (PAY_3...
10,,M0T11N17,0.421718,0.071532,(PAY_1 < 1.5 or PAY_1 is NA) & (PAY_2 >= 1.5) & (PAY_AMT6 < 8260.5...
11,,M0T20N21,0.357396,0.042520,(BILL_AMT3 < 223384.5 or BILL_AMT3 is NA) & (PAY_1 >= 1.5) & (PAY_...
12,,M0T0N20,0.339552,0.003408,(PAY_1 >= 1.5) & (PAY_2 >= -0.5) & (PAY_3 < -0.5)
13,,M0T27N18,-0.332339,0.014672,(BILL_AMT6 < 26378.5 or BILL_AMT6 is NA) & (PAY_5 >= 1.0) & (PAY_6...
14,,M0T11N20,0.311801,0.055364,(BILL_AMT1 >= 2401.5 or BILL_AMT1 is NA) & (PAY_1 >= 1.5) & (PAY_5...
15,,M0T48N21,-0.309006,0.013218,(BILL_AMT1 < 140617.5 or BILL_AMT1 is NA) & (PAY_4 >= 0.5) & (PAY_...
16,,M0T36N14,0.292427,0.567314,(BILL_AMT2 >= 4311.5 or BILL_AMT2 is NA) & (PAY_1 < 1.5 or PAY_1 i...
17,,M0T18N15,0.275840,0.050709,(BILL_AMT4 < 2093.5) & (PAY_1 >= 0.5) & (PAY_1 < 1.5 or PAY_1 is NA)
18,,M0T5N22,-0.269707,0.008313,(EDUCATION in {high school}) & (PAY_1 >= 1.5) & (PAY_6 >= 1.0)
19,,M0T44N17,0.240054,0.448647,(PAY_4 < 0.5 or PAY_4 is NA) & (PAY_AMT2 < 19737.5 or PAY_AMT2 is ...

See the whole table with table.as_data_frame()

`M0T14N15, M0T4N15, M0T22N15, M0T30N15`といった形で表示されているのは同じルールが複数の木の間で作成されたため。同じルールなので一つのみLassoに投入される  
（あえて全て投入する場合はハイパーパラメータに`remove_duplicates=False`を指定）

In [35]:
# オブザベーションが各ルールに該当するか。該当すれば1
rule_observation = rfit.predict_rules(frame_test, ['M0T43N20', 'M0T42N16', 'M0T28N21', 'M0T41N18', 'M0T37N21'])   # 上位5ルール
print(rule_observation.shape)
rule_observation

(5941, 5)

M0T43N20,M0T42N16,M0T28N21,M0T41N18,M0T37N21
0,0,0,0,0
0,0,0,0,0
0,0,1,0,0
0,0,0,0,0
0,0,0,0,0
0,0,0,0,1
0,0,0,0,0
0,0,0,0,0
0,0,0,0,0
0,0,0,0,0

In [33]:
# ルール"M0T28N21"に該当しているindex=2のオブザベーションを表示してみる
# ルール"M0T28N21" : (PAY_2 < 1.5) & (PAY_3 >= 1.5) & (PAY_AMT1 >= 853.5 or PAY_AMT1 is NA)
frame_test[2,:]

ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,BILL_AMT2,BILL_AMT3,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default_payment_next_month
17,20000,F,graduate school,single,24,0,0,2,2,2,2,15376,18010,17428,18338,17905,19104,3200,0,1500,0,1650,0,1

Rule Importanceの'support'とは、各ルールに該当するオブザベーションの割合

In [13]:
rfit.predict_rules(frame_train, ['M0T43N20']).mean()

[0.06068415146099173]

In [30]:
rfit.rule_importance().as_data_frame().iloc[0,:]

variable                                                                    M0T43N20
coefficient                                                                 0.793195
support                                                                     0.060684
rule           (PAY_2 >= 1.5) & (PAY_5 >= 1.0) & (PAY_AMT3 < 12250.5 or PAY_AMT3 ...
Name: 0, dtype: object

In [16]:
rule = rfit.rule_importance().as_data_frame()    # pandas dataframeへ変換
rule

,,variable,coefficient,support,rule
0,,M0T43N20,7.931945e-01,0.060684,(PAY_2 >= 1.5) & (PAY_5 >= 1.0) & (PAY_AMT3 < 12250.5 or PAY_AMT3 ...
1,,M0T42N16,7.926013e-01,0.002411,(AGE >= 59.5) & (PAY_3 < -0.5 or PAY_3 is NA) & (PAY_AMT1 < 853.5)
2,,M0T28N21,5.112636e-01,0.039486,(PAY_2 < 1.5) & (PAY_3 >= 1.5) & (PAY_AMT1 >= 853.5 or PAY_AMT1 is...
3,,M0T41N18,-4.876343e-01,0.021281,(BILL_AMT1 >= 13204.5) & (PAY_1 >= 1.5) & (PAY_AMT1 < 853.5)
4,,M0T37N21,4.820868e-01,0.097302,(PAY_1 >= 1.5) & (PAY_3 >= -0.5 or PAY_3 is NA) & (PAY_AMT5 < 2832...
...,...,...,...,...,...
160,,linear.PAY_AMT6,-9.851240e-07,1.000000,
161,,linear.BILL_AMT5,-9.562083e-07,1.000000,
162,,linear.PAY_AMT3,9.532023e-07,1.000000,
163,,linear.BILL_AMT2,8.274567e-07,1.000000,
164,,linear.BILL_AMT4,1.747303e-07,1.000000,

In [18]:
rule.to_csv('../tmp/rule.csv')

### ルール生成の設定を変えてみる

In [63]:
rfit2 = H2ORuleFitEstimator(seed=123,
                            min_rule_length=1,    # 分岐の深さの最小値
                            max_rule_length=2,   # 分岐の深さの最大値（1次の交互作用まで）
                            max_num_rules=50,  # 最大で50ルールまでは作成可能
                           #remove_duplicates=False,
                           )
rfit2.train(x=x_cols, y=y_col, training_frame=frame_train, validation_frame=frame_test)

rulefit Model Build progress: |██████████████████████████████████████████████████| (done) 100%
Model Details
=============
H2ORuleFitEstimator :  RuleFit
Model Key:  RuleFit_model_python_1675561998375_679


Rulefit Model Summary:

,,family,link,regularization,number_of_predictors_total,number_of_active_predictors,number_of_iterations,rule_ensemble_size,number_of_trees,number_of_internal_trees,min_depth,max_depth,mean_depth,min_leaves,max_leaves,mean_leaves
0,,binomial,logit,Lasso (lambda = 1.346E-4 ),328,39,4,300.0,100.0,100.0,0.0,2.0,1.5,0.0,4.0,3.0

ModelMetricsBinomialGLM: rulefit
** Reported on train data. **

MSE: 0.13657033743849756
RMSE: 0.36955424153769034
LogLoss: 0.43777362876157283
Null degrees of freedom: 24058
Residual degrees of freedom: 24019
Null deviance: 25409.37990548039
Residual deviance: 21064.79146874936
AIC: 21144.79146874936
AUC: 0.7501833186180569
AUCPR: 0.5336151685468256
Gini: 0.5003666372361137

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.24904662968147848:

                0       1   Error               Rate
0      0  15766.0  2978.0  0.1589   (2978.0/18744.0)
1      1   2292.0  3023.0  0.4312    (2292.0/5315.0)
2  Total  18058.0  6001.0   0.219   (5270.0/24059.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold         value    idx
0                        max f1   0.249047      0.534288  282.0
1                        max f2   0.125405      0.613747  362.0
2                  max f0point5   0.500048      0.579940  135.0
3                  max accuracy   0.500048      0.821564  135.0
4                 max precision   0.827096      1.000000    0.0
5                    max recall   0.093905      1.000000  397.0
6               max specificity   0.827096      1.000000    0.0
7              max absolute_mcc   0.370016      0.415503  208.0
8    max min_per_class_accuracy   0.175710      0.693697  330.0
9   max mean_per_class_accuracy   0.209165      0.705682  303.0
10                      max tns   0.827096  18744.000000    0.0
11                      max fns   0.827096   5314.000000    0.0
12                      max fps   0.090525  18744.000000  399.0
13                      max tps   0.093905   5315.000000  397.0
14                      max tnr   0.827096      1.000000    0.0
15                      max fnr   0.827096      0.999812    0.0
16                      max fpr   0.090525      1.000000  399.0
17                      max tpr   0.093905      1.000000  397.0

Gains/Lift Table: Avg response rate: 22.09 %, avg score: 22.09 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.010225,0.755717,3.551375,3.551375,0.784553,0.776924,0.784553,0.776924,0.036312,0.036312,255.137477,255.137477,0.033485
1,2,0.021489,0.739304,3.290571,3.414667,0.726937,0.746506,0.754352,0.760979,0.037065,0.073377,229.057079,241.466708,0.066602
2,3,0.039943,0.736605,3.507113,3.457379,0.774775,0.736649,0.763788,0.749738,0.064722,0.138100,250.711313,245.737889,0.125989
3,4,0.040027,0.736098,4.526623,3.459600,1.000000,0.736172,0.764278,0.749710,0.000376,0.138476,352.662277,245.959954,0.126365
4,5,0.058232,0.728470,3.121096,3.353772,0.689498,0.731825,0.740899,0.744119,0.056820,0.195296,212.109606,235.377190,0.175930
5,6,0.100087,0.597052,2.944328,3.182547,0.650447,0.647048,0.703073,0.703525,0.123236,0.318532,194.432762,218.254665,0.280387
6,7,0.151752,0.413279,2.130390,2.824335,0.470636,0.480664,0.623939,0.627651,0.110066,0.428598,113.038964,182.433488,0.355348
7,8,0.200050,0.291788,1.593278,2.527121,0.351979,0.349796,0.558280,0.560569,0.076952,0.505550,59.327772,152.712142,0.392127
8,9,0.300179,0.186231,1.093605,2.048952,0.241594,0.232029,0.452645,0.450980,0.109501,0.615052,9.360500,104.895179,0.404158
9,10,0.401845,0.175454,0.875344,1.752030,0.193377,0.182727,0.387050,0.383112,0.088993,0.704045,-12.465553,75.202962,0.387891
10,11,0.818862,0.110144,0.498998,1.113906,0.110236,0.114191,0.246079,0.246160,0.208090,0.912135,-50.100221,11.390626,0.119722
11,12,0.921734,0.108221,0.457235,1.040617,0.101010,0.108933,0.229888,0.230845,0.047037,0.959172,-54.276538,4.061701,0.048054
12,13,1.000000,0.090525,0.521655,1.000000,0.115242,0.103976,0.220915,0.220915,0.040828,1.000000,-47.834459,0.000000,0.000000

ModelMetricsBinomialGLM: rulefit
** Reported on validation data. **

MSE: 0.13650944156629938
RMSE: 0.3694718413713004
LogLoss: 0.43743575659884465
Null degrees of freedom: 5940
Residual degrees of freedom: 5901
Null deviance: 6295.988467440929
Residual deviance: 5197.611659907472
AIC: 5277.611659907472
AUC: 0.7593079327939283
AUCPR: 0.5526196176913595
Gini: 0.5186158655878566

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.23193674762395936:

               0       1   Error              Rate
0      0  3903.0   717.0  0.1552    (717.0/4620.0)
1      1   572.0   749.0   0.433    (572.0/1321.0)
2  Total  4475.0  1466.0   0.217   (1289.0/5941.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold        value    idx
0                        max f1   0.231937     0.537496  266.0
1                        max f2   0.111074     0.620554  369.0
2                  max f0point5   0.519634     0.582586  104.0
3                  max accuracy   0.522138     0.822084  101.0
4                 max precision   0.824107     1.000000    0.0
5                    max recall   0.093915     1.000000  398.0
6               max specificity   0.824107     1.000000    0.0
7              max absolute_mcc   0.412049     0.410601  155.0
8    max min_per_class_accuracy   0.175628     0.698713  317.0
9   max mean_per_class_accuracy   0.202556     0.706427  285.0
10                      max tns   0.824107  4620.000000    0.0
11                      max fns   0.824107  1312.000000    0.0
12                      max fps   0.092187  4620.000000  399.0
13                      max tps   0.093915  1321.000000  398.0
14                      max tnr   0.824107     1.000000    0.0
15                      max fnr   0.824107     0.993187    0.0
16                      max fpr   0.092187     1.000000  399.0
17                      max tpr   0.093915     1.000000  398.0

Gains/Lift Table: Avg response rate: 22.24 %, avg score: 21.81 %

,group,cumulative_data_fraction,lower_threshold,lift,cumulative_lift,response_rate,score,cumulative_response_rate,cumulative_score,capture_rate,cumulative_capture_rate,gain,cumulative_gain,kolmogorov_smirnov
0,1,0.010268,0.753109,3.833807,3.833807,0.852459,0.773098,0.852459,0.773098,0.039364,0.039364,283.380698,283.380698,0.037416
1,2,0.021209,0.739304,3.459500,3.640712,0.769231,0.745133,0.809524,0.758672,0.037850,0.077214,245.950038,264.071230,0.072019
2,3,0.038714,0.736605,3.545988,3.597880,0.788462,0.736640,0.800000,0.748709,0.062074,0.139288,254.598789,259.788039,0.129332
3,4,0.045615,0.736034,3.290744,3.551413,0.731707,0.736034,0.789668,0.746792,0.022710,0.161998,229.074426,255.141330,0.149661
4,5,0.055883,0.728470,3.170263,3.481383,0.704918,0.729356,0.774096,0.743588,0.032551,0.194550,217.026346,248.138276,0.178316
5,6,0.101330,0.570025,2.848322,3.197452,0.633333,0.645307,0.710963,0.699509,0.129447,0.323997,184.832198,219.745184,0.286335
6,7,0.150143,0.371652,2.031562,2.818407,0.451724,0.455132,0.626682,0.620059,0.099167,0.423164,103.156177,181.840687,0.351086
7,8,0.200640,0.282342,1.589064,2.509008,0.353333,0.337544,0.557886,0.548956,0.080242,0.503407,58.906384,150.900845,0.389337
8,9,0.320148,0.186008,1.114836,1.988576,0.247887,0.220164,0.442166,0.426221,0.133232,0.636639,11.483618,98.857611,0.406985
9,10,0.403972,0.172614,0.866959,1.755841,0.192771,0.180767,0.390417,0.375289,0.072672,0.709311,-13.304087,75.584059,0.392644
10,11,0.820232,0.110144,0.523751,1.130567,0.116458,0.113565,0.251385,0.242467,0.218017,0.927328,-47.624871,13.056728,0.137717
11,12,0.921225,0.108221,0.382275,1.048533,0.085000,0.108909,0.233145,0.227825,0.038607,0.965935,-61.772521,4.853266,0.057493
12,13,1.000000,0.092126,0.432438,1.000000,0.096154,0.104196,0.222353,0.218086,0.034065,1.000000,-56.756245,0.000000,0.000000

In [64]:
# 学習とテストデータにおけるAUC
rfit2.auc(), rfit2.auc(valid=True)

(0.7501833186180569, 0.7593079327939283)

In [65]:
# 特徴量重要度（Lassoの回帰係数）とルール（交互作用）の表示
rfit2_rule = rfit2.rule_importance().as_data_frame()
print(rfit2_rule.shape)
rfit2_rule

(19, 5)

,,variable,coefficient,support,rule
0,,"M1T35N7, M1T16N7, M1T34N7, M1T24N7, M1T0N7, M1T11N7",-0.984044,0.818945,(PAY_1 < 1.5 or PAY_1 is NA) & (PAY_2 < 1.5 or PAY_2 is NA)
1,,"M0T34N4, M0T26N4",-0.962259,0.147762,(PAY_2 >= 1.5)
2,,"M1T18N10, M1T35N10, M1T16N10",0.910978,0.100669,(PAY_1 >= 1.5) & (PAY_2 >= -0.5 or PAY_2 is NA)
3,,"M1T25N7, M1T26N7",-0.580401,0.807099,(PAY_2 < 1.5 or PAY_2 is NA) & (PAY_4 < 0.5 or PAY_4 is NA)
4,,M1T43N9,0.436397,0.143522,(PAY_2 >= 1.5) & (PAY_AMT3 < 12250.5 or PAY_AMT3 is NA)
5,,"M1T30N7, M1T4N7, M1T1N7, M1T5N7",-0.357387,0.839353,(PAY_1 < 1.5 or PAY_1 is NA) & (PAY_5 < 1.0 or PAY_5 is NA)
6,,M1T28N9,-0.350951,0.657758,(PAY_3 < 1.5 or PAY_3 is NA) & (PAY_AMT1 >= 853.5 or PAY_AMT1 is NA)
7,,"M0T36N4, M0T5N4, M0T2N4, M0T35N4, M0T0N4",-0.291981,0.105075,(PAY_1 >= 1.5)
8,,M1T15N7,-0.291175,0.824598,(PAY_3 < 1.5 or PAY_3 is NA) & (PAY_5 < 1.0 or PAY_5 is NA)
9,,"M1T42N9, M1T31N9, M1T7N9",-0.272050,0.684650,(PAY_1 < 1.5 or PAY_1 is NA) & (PAY_AMT1 >= 853.5 or PAY_AMT1 is NA)
10,,M1T43N7,-0.240834,0.807847,(PAY_2 < 1.5 or PAY_2 is NA) & (PAY_6 < 1.0 or PAY_6 is NA)
11,,linear.PAY_2,-0.168031,1.000000,
12,,linear.PAY_1,0.127447,1.000000,
13,,M1T40N7,0.103051,0.809967,(PAY_2 < 1.5 or PAY_2 is NA) & (PAY_3 < 1.5 or PAY_3 is NA)
14,,"M1T17N7, M1T20N7",-0.102439,0.812503,(PAY_1 < 1.5 or PAY_1 is NA) & (PAY_3 < 1.5 or PAY_3 is NA)
15,,"M1T49N7, M1T14N7",0.071467,0.815080,(PAY_2 < 1.5 or PAY_2 is NA) & (PAY_5 < 1.0 or PAY_5 is NA)
16,,linear.PAY_3,0.049000,1.000000,
17,,linear.PAY_6,0.020763,1.000000,
18,,linear.PAY_4,-0.019293,1.000000,

In [31]:
# H2O-3の終了
h2o.cluster().shutdown()

H2O session _sid_b0e1 closed.